version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
#      - pgconf:/etc/postgresql
#      - pglog:/var/log/postgresql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql

#    command: chown postgres /var/lib/postgresql/data/
  web:
    image: schulzdaniel/django:1.1
    command: python manage.py runserver 0.0.0.0:8123
    volumes:
      - .:/code
    ports:
      - "8123:8123"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2

networks:
  docker-network:
    driver: bridge

volumes:
  pgdata:
#  pgconf:
#  pglog:
